name: Build & Deploy
run-name: Build & Deploy ${{ github.repository }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy landing page to gh-pages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18']

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@394d78e5b40cc35c170eb909b1f81551f37feb05 # v2.5.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # v3.5.3

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        working-directory: ./app
        run: npm ci --prefer-offline

      - name: Build & Deploy
        working-directory: ./app
        run: |
          git config --global '${user_name}'
          git config --global user.email '${user_email}'
          git remote set-url origin https://${github_token}@github.com/${github_repository}
          npm run deploy
        env:
          user_name: 'seyLu-bot'
          user_email: '141534257+seyLu-bot@users.noreply.github.com'
          github_token: ${{ github.SEYLUBOT_PAT }}
          github_repository: ${{ github.repository }}
