name: Build & Deploy
run-name: Build & Deploy ${{ github.repository }}

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy landing page to gh-pages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18']

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@394d78e5b40cc35c170eb909b1f81551f37feb05 # v2.5.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v3.5.3

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./app/package-lock.json

      - name: Install Dependencies
        working-directory: ./app
        run: npm ci --prefer-offline

      - name: Build & Deploy
        working-directory: ./app
        run: |
          git config --global user.name ${user_name}
          git config --global user.email ${user_email}
          git remote set-url origin https://${github_token}@github.com/${github_repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.SEYLUBOT_PAT}}
          github_repository: ${{ github.repository }}
